import importlib.util, os
B = chr(92)
os.environ["HERMES_HOME"] = "D:" + B + "myagent" + B + ".hermes"
os.chdir("D:" + B + "myagent" + B + "workspace")
spec = importlib.util.spec_from_file_location("wgp", r"D:\myagent\workspace\write-guard\handler.py")
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
CFG = "D:/myagent/.hermes/config.yaml"
HD = "D:/myagent/.hermes/plugins/write-guard/handler.py"
GD = "D:/myagent/.hermes/plugins/write-guard"
WS = "D:/myagent/workspace/a.txt"
def j(cmd):
    r = m._judge_terminal(cmd, "terminal")
    a = (r or {}).get("action") or "PASS"
    print("%-6s | %s" % (a, cmd))
print("=== S-1 FP \u8d1f\u4f8b ===")
j("curl -o " + CFG + " http://x")
j("curl -O http://x/a.txt")
j("curl -oL http://x/a.txt")
j("curl -sSL -o out.txt http://x")
j("sort -oD:/myagent/workspace/out.txt d.txt")
j("grep -o config D:/myagent/workspace/f.txt")
j("wget -O" + CFG + " http://x")
j("curl -o=" + CFG + " http://x")
j("tar xzf D:/myagent/workspace/a.tgz")
j("curl -O -o" + CFG + " http://x")
print("=== S-3 FP \u8d1f\u4f8b ===")
j("type f 2>&1 > " + WS)
j("echo x 2>&1 | findstr y")
j("echo x > " + WS + " 2>&1 & echo done")
j('curl "https://x?a=1&b=2"')
j("curl https://x?a=1&b=2")
j("echo x >&2")
j("start /b x & dir")
j("echo a&b")
print("=== S-3 \u6f0f\u62e6\u65b9\u5411 ===")
j("echo x & cp evil " + GD)
j("echo x > " + CFG + "&dir")
j("echo x 2>&1> " + CFG)
j("echo x 2> " + CFG)
j("copy evil " + GD + " & echo done")
print("=== S-4 ===")
j("runas /user:admin cp evil " + GD)
j("sudo cp evil " + GD)
j("LANG=C cp evil " + GD)
j("env | grep config")
j("time ls D:/myagent/workspace")
j("nohup cp evil " + GD + " &")
j("sudo -u root cp evil " + GD)
j("env FOO=1 cp evil " + GD)
j("time cp evil " + GD)
j("cp evil " + GD)
j("sudo cat " + HD)
j("sudo truncate -s 0 " + CFG)
print("=== S-5 ===")
j("cmd /c copy evil " + CFG)
j("cmd /q /c copy evil " + CFG)
j("pwsh -Command Copy-Item evil " + CFG)
j('cmd /c "copy evil ' + CFG + '"')
j("cmd /c dir D:" + B + "myagent" + B + "workspace")
j("pwsh -Command Get-Date")
j("sh -c cp evil " + GD)
j("cmd /c copy evil D:/myagent/workspace/out.txt")
j("bash -lc 'cp evil " + GD + "'")
j("pwsh -NoProfile -Command Copy-Item evil " + CFG)
j("cmd /c echo x > " + CFG)
j("powershell -Command Set-Content " + CFG + " x")
