import importlib.util, os
B = chr(92)
os.environ["HERMES_HOME"] = "D:" + B + "myagent" + B + ".hermes"
os.chdir("D:" + B + "myagent" + B + "workspace")
W = r"D:\myagent\workspace\write-guard"
spec = importlib.util.spec_from_file_location("wg", W + B + "handler.py")
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
CFG = "D:" + B + "myagent" + B + ".hermes" + B + "config.yaml"
CFGS = CFG.replace(B, "/")
WSX = "D:/myagent/workspace/x.txt"
def j(cmd):
    r = m._judge_terminal(cmd, "terminal")
    return "PASS" if r is None else str(r.get("action"))
print("== F-11-1 PS 冒号粘连（三代全 PASS 声称）==")
print("a1 Copy-Item -Destination:CFG 非保护   :", j("Copy-Item -Destination:" + CFGS + " " + WSX))
print("a2 Tee-Object -FilePath:CFG -InputObj  :", j("Tee-Object -FilePath:" + CFGS + " -InputObject x"))
print("a3 Copy-Item -Destination:'CFG'        :", j("Copy-Item -Destination:'" + CFGS + "' " + WSX))
print("a4 对照等号形 -Destination=CFG（应附录）:", j("Copy-Item -Destination=" + CFGS + " " + WSX))
print("== F-11-2 引号包选项词 ==")
print("b1 curl \"-o\" CFG url                   :", j('curl "-o" ' + CFGS + " http://x"))
print("b2 curl '-o' CFG url                   :", j("curl '-o' " + CFGS + " http://x"))
print("b3 curl \"--output\" CFG url             :", j('curl "--output" ' + CFGS + " http://x"))
print("b4 NEG grep \"-o\" CFG（门外）           :", j('grep "-o" ' + CFGS))
print("b5 NEG curl \"-O\" url（大写红线向）      :", j('curl "-O" http://x/a.zip'))
print("== F-11-3 命名支绑定词含源参 ==")
print("c1 Copy-Item -Destination WS -Path CFG :", j("Copy-Item -Destination " + WSX + " -Path " + CFGS))
print("c2 同上 -LiteralPath                   :", j("Copy-Item -Destination " + WSX + " -LiteralPath " + CFGS))
print("c3 反向锁形 -Path CFG -Destination WS  :", j("Copy-Item -Path " + CFGS + " -Destination " + WSX))
print("c4 封堵锁形 -Destination CFG 非保护    :", j("Copy-Item -Destination " + CFGS + " " + WSX))
print("c5 单标志 -Path CFG 非保护末位(Q-11-1) :", j("Copy-Item -Path " + CFGS + " " + WSX))
print("c6 Tee -FilePath CFG 末位非保护        :", j("Tee-Object -FilePath " + CFGS + " x"))
print("== F-11-4 cluster 尾 o + 空格值 ==")
print("d1 curl -so CFG url                    :", j("curl -so " + CFGS + " http://x"))
print("d2 curl -sSLfo CFG url                 :", j("curl -sSLfo " + CFGS + " http://x"))
print("d3 wget -qO CFG url                    :", j("wget -qO " + CFGS + " http://x"))
print("d4 sort -ro CFG d.txt                  :", j("sort -ro " + CFGS + " d.txt"))
print("d5 NEG curl -so 非保护 url             :", j("curl -so " + WSX + " http://x"))
print("d6 NEG grep -o CFG（门外）             :", j("grep -o " + CFGS))
print("d7 NEG mount -o rem,rw（门内不变）      :", j("mount -o rem,rw /x"))
print("d8 NEG curl -O URL 红线                :", j("curl -O http://x/a.zip"))
print("d9 F-10-2 归正不回潮 sort ws/o CFG     :", j("sort D:/myagent/workspace/o " + CFGS))
print("d10 同上 curl http://x/o CFG           :", j("curl http://x/o " + CFGS))
